/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-ZEWiLzgRlUVBOSIka2ff-oM1JKZb7Wz11IqDlU4ejcDW5n-dyB9nvi-2UZhKGlX62e5O25MzT4jf6nvYtMjwcw4Z52ddt0ZLVlmbR4IJVS-tyn1ah2ARqiIv",
  "tt": "tt-1-MEoT3ua1cNGjjdS6VPJz9M3H5MAwSnWqkY2dsyxNn58=",
  "version": "2020-11-20"
}

export default ebconfig;